# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-12 14:40
from __future__ import unicode_literals

import SequoiaApp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('bank_name', models.CharField(max_length=256)),
                ('bank_account_number', models.CharField(max_length=256)),
                ('bank_branch_name', models.CharField(max_length=256)),
                ('bank_ifsc_code', models.CharField(max_length=256)),
                ('PAN', models.CharField(max_length=10)),
                ('mobile_number', models.CharField(max_length=10)),
                ('GSTIN', models.CharField(max_length=15, validators=[SequoiaApp.models.validate_GSTIN])),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Remitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('account_number', models.CharField(max_length=256)),
                ('mobile_number', models.CharField(max_length=10)),
                ('PAN', models.CharField(max_length=10)),
                ('GSTIN', models.CharField(max_length=15, validators=[SequoiaApp.models.validate_GSTIN])),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Remitter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RTGS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheque_number', models.CharField(max_length=15)),
                ('amount_in_figure', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_in_word', models.CharField(max_length=1024)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RTGS', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RTGS', to='SequoiaApp.Customer')),
                ('remitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RTGS', to='SequoiaApp.Remitter')),
            ],
            options={
                'verbose_name_plural': 'RTGS',
            },
        ),
    ]
