# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-05 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('bank_name', models.CharField(max_length=256)),
                ('bank_account_number', models.CharField(max_length=256)),
                ('bank_branch_name', models.CharField(max_length=256)),
                ('bank_ifsc_code', models.CharField(max_length=256)),
                ('PAN', models.CharField(max_length=10)),
                ('mobile_number', models.CharField(max_length=10)),
                ('GSTIN', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Remitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('account_number', models.CharField(max_length=256)),
                ('mobile_number', models.CharField(max_length=10)),
                ('PAN', models.CharField(max_length=10)),
                ('GSTIN', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RTGS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheque_number', models.CharField(max_length=15)),
                ('amount_in_figure', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_in_word', models.CharField(max_length=1024)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RTGS', to='SequoiaApp.Customer')),
                ('remitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RTGS', to='SequoiaApp.Remitter')),
            ],
            options={
                'verbose_name_plural': 'RTGS',
            },
        ),
    ]
