# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-17 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SequoiaApp', '0002_auto_20180217_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='bank_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='rtgs',
            name='cheque_number',
            field=models.CharField(max_length=16),
        ),
    ]
